services:
  kudos-blockchain:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kudos-blockchain
    restart: always
    volumes:
      - ../blockchain:/app/blockchain
    networks:
      - kudos-network
    ports:
      - "8000:8000"
    depends_on:
      kudos-db:
        condition: service_healthy
    environment:
      - DB_URL=postgresql://kudos_user:kudos_pass@kudos-db:5432/kudos

  kudos-db:
    image: postgres:latest
    container_name: kudos-db
    environment:
      POSTGRES_USER: kudos_user
      POSTGRES_PASSWORD: kudos_pass
      POSTGRES_DB: kudos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kudos_user -d kudos"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - kudos-network

networks:
  kudos-network:
    name: kudos-network